---

# AnDEVy - A playbook to install Ansible and git on a fresh Ubuntu box
# Written by Jordy de Muijnk and tested on Ubuntu 20.04 LTS
# Twitter: @manderait
# Feel free to use, modify and distribute

- hosts: server1
  tasks:

  - name: Set timezone to Europe/Amsterdam
    command: timedatectl set-timezone Europe/Amsterdam
    become: true

  - name: Updating Ubuntu packages to the latest version first
    apt:
        name: "*"
        state: latest
    become: true
        
  - name: Install git
    package: name=git state=latest
    become: true
 
  - name: Install pip3
    package: name=python3-pip state=latest
    become: true

  - name: Install Ansible
    pip:
        name: ansible
           
  - name: Cloning Git-repository AnDEVy to managed node
    command: git clone https://github.com/manderait/ansible-playbooks.git
    args:
      chdir: ~/Downloads/

  - name: Installing dependencies for Brackets
    package: name=libcurl4 state=latest
    package: name=libgconf-2-4 state=latest
    package: name=gconf-service state=latest
    become: true

#   Unfortunately this section is not working on Ubuntu 20.04 LTS Beta. Playbooks hangs when executed. Manual install works fine.
    
#  - name: Change directory to the /tools directory & install Brackets
#    shell: 
#      cmd: cd ~/Downloads/ansible-playbooks/tools
#      cmd: sudo dpkg -i Brackets-1_14_1.deb
    
  - name: Autoclean useless packages from cache
    apt:
        autoclean: yes
    become: true
            
  - name: Autoremove dependencies that are no longer required
    apt:
        autoremove: yes
    become: true    
      
  - name: Set variable to disable hostkey checking (ONLY USE IN LAB ENVIRONMENTS!)
    shell: 
      cmd: export ANSIBLE_HOST_KEY_CHECKING=false

