---

# AnDEVy - A playbook to install Ansible and git on a fresh Ubuntu box
# Written by Jordy de Muijnk and tested on Ubuntu 20.04 LTS
# Twitter: @manderait
# Feel free to use, modify and distribute

- hosts: localhost
  tasks:

  - name: Set timezone to Europe/Amsterdam
    timezone:
      name: Europe/Amsterdam

  - name: Updating Ubuntu packages to the latest version first
    apt:
        name: "*"
        state: latest
    
  - name: Install git
    apt:
        name: git
        state: latest
    
  - name: Install pip3
    apt:
        name: python3-pip
        state: latest

  - name: Install Ansible
    pip:
        name: ansible

  - name: Install sshpass
    apt:
        name: sshpass
        state: latest
        
  - name: Install Brackets
    apt:
        deb: "{{ playbook_dir }}/tools/Brackets-1_14_1.deb"
        
  - name: Autoclean useless packages from cache
    apt:
        autoclean: yes
    
  - name: Autoremove dependencies that are no longer required
    apt:
        autoremove: yes


# Set variable to disable hostkey checking
# export ANSIBLE_HOST_KEY_CHECKING=false

