---

# AnDEVy - A playbook to install Ansible and git on a fresh Ubuntu box
# Written by Jordy de Muijnk and tested on Ubuntu 20.04 LTS
# Twitter: @manderait
# Feel free to use, modify and distribute

- hosts: server1
  tasks:

  - name: Set timezone to Europe/Amsterdam
    command: timedatectl set-timezone Europe/Amsterdam
    become: true

  - name: Updating Ubuntu packages to the latest version first
    apt:
        name: "*"
        state: latest
    become: true
        
  - name: Install git
    package: name=git state=latest
    become: true
 
  - name: Install pip3
    package: name=python3-pip state=latest
    become: true

  - name: Install Ansible
    pip:
        name: ansible
    
#  - name: Install Brackets
#    apt:
#        deb: "{{ playbook_dir }}/tools/Brackets-1_14_1.deb"
#        become: true
        
  - name: Autoclean useless packages from cache
    apt:
        autoclean: yes
    become: true
            
  - name: Autoremove dependencies that are no longer required
    apt:
        autoremove: yes
    become: true    

# Set variable to disable hostkey checking
# export ANSIBLE_HOST_KEY_CHECKING=false

